version: '3'
services:
  learn-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: learn-db
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: plantshop
    expose:
      - 5432
  plant-shop-container:
    image: plant-shop-image
    ports:
      - "8080:8080"
    environment:
      DB_HOST: plantshop
      DB_PORT: 5432
      SPRING_DATASOURCE_URL: jdbc:postgresql://plantshop:5432/plantshop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SECRET_KEY: 703273357638792F423F4528482B4D6251655368566D597133743677397A2443
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - plantshop
volumes:
  learn-db:
    driver: local