spring:
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/plantshop
    username: postgres
    password: ${DB_PASSWORD:admin}
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
    hikari:
      maximum-pool-size: 10
      idle-timeout: 10000
      connection-timeout: 30000
      max-lifetime: 600000
      auto-commit: false
      data-source-properties:
        stringtype: unspecified
        prepareThreshold: 0  # To avoid switching to auto-commit mode for prepared statements
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        jdbc:
          lob:
            non_contextual_creation: true  # Required to avoid the use of PostgreSQL's LargeObject API
        enable_lazy_load_no_trans: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

com:
  shop:
    securityConfig:
      authWitheList:
        - "/api/v1/**"
        - "/v3/api-docs/**"
        - "v3/api-docs/**"
        - "/swagger-ui/**"
        - "swagger-ui/**"
      adminEndpointsList:
        - "/api/admin/v1/**"
      securedEndpoints:
        - "/api/admin/v1/**"
        - "/api/user/v1/**"
        - "/api/moderator/**"
