spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/plantshop
    username: postgres
    password: ${DB_PASSWORD:admin}
    tomcat:
      connection-properties: stringtype=unspecified
    hikari:
      data-source-properties:
        stringtype: unspecified
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

